# Generated by Django 4.0.5 on 2022-06-17 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='level',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tree_id',
        ),
    ]
